name: Lint and test code

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'main'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'main'
    tags-ignore:
      - '*'

jobs:
  test-and-lint:
    if: ${{ github.repository == 'nameless-on-discord/nameless' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -U -r requirements_core.txt -r requirements_dev.txt

      - name: Create dummy config file
        run: |
          cp NamelessConfig_example.py NamelessConfig.py

      - name: Code format checking (black)
        run: |
          black . --check --diff

      - name: Code format checking (isort)
        run: |
          isort . --check --diff

      - name: Type annotation checking (pyright)
        run: |
          pyright

      - name: Linting (flake8)
        run: |
          flake8 --select=E

      - name: Linting (pylint)
        run: |
          pylint **/*.py --disable=W,R,C

      - name: Run tests and return coverages (pytest & friends)
        run: |
          pytest --cov-report term-missing --cov=nameless.database --cov=nameless.commons.Utility tests/
